# Site settings
title: MathML Association
email: directors@mathml-association.org
description:
  An charitable organization for the adoption of MathML.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mathml-association.com" # the base hostname & protocol for your site
twitter_username: mathml3
github_username:  mathml

# Build settings
markdown: kramdown

# Header
header:
  - title: News
    url: /news.html
  - title: Projects
    url: /projects.html
  - title: About us
    url: /about.html
    sub:
      - title: Statutes
        url: /statutes.html
      - title: Members
        url: /members.html
      - title: FAQ
        url: /faq.html
  - title: Donate
    url: /donate.html
  - title: Contact
    url: /contact.html
