# Site settings
title: MathML Association
email: directors@mathml-association.org
description: A math group acting on the Web
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mathml-association.com" # the base hostname & protocol for your site
twitter_username: mathml3
github_username:  mathml

# Build settings
markdown: kramdown

# Header
header:
  - title: News
    url: /news.html
  - title: Projects
    url: /projects.html
  - title: About us
    url: /about.html
    sub:
      - title: Directors
        url: /directors.html
      - title: Bylaws
        url: /non-profit-corporate-by-laws.html
      - title: COIP
        url: conflict-of-interest-policy.html
      - title: Meetings
        url: meetings/meetings.html
      - title: FAQ
        url: /faq.html
  - title: Donate
    url: /donate.html
  - title: Contact
    url: /contact.html
