# Site settings
title: MathML Association
email: info@mathml-association.org
emaildomain: mathml-association.org
description: A group action for MathML
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mathml-association.org" # the base hostname & protocol for your site
twitter_username: mathml3
github_username:  mathml
reedit_username: mathml

# Build settings
markdown: kramdown

# Header
header:
  - title: Manifesto
    url: /legal-documents/manifesto.html
  - title: News
    url: /news.html
    sub:
      - title: Reports
        url: /reports/index.html
      - title: Meetings
        url: /meetings/meetings.html
      - title: Twitter
        url: https://twitter.com/mathml3
      - title: Reedit
        url: https://www.reddit.com/user/mathml
  - title: About
    url: /about.html
    sub:
      - title: People
        url: /people/index.html
      - title: Logos
        url: /logo/index.html
      - title: Documents
        url: /legal-documents/index.html
      - title: FAQ
        url: /faq.html
  - title: Affiliates
    url: /affiliates/index.html
    sub:
      - title: Sponsors
        url: /affiliates/sponsors.html
      - title: Partners
        url: /affiliates/partners.html
      - title: Friends
        url: /affiliates/friends.html
      - title: Donate
        url: /affiliates/donate.html
  - title: Contact
    url: /contact.html
